### ISSUE TITLE
In new version 4.0.0 - package distributed over npm doesn't have src directory

### ISSUE THREAD

**Issue by adelura** [gajus/swing#88] opened 2016-11-24 21:18 UTC
1. When I install library via `npm`, I can't see `src` directory in `node_modules/swing/`. Bower distribution does have one.
2. Is there any reasoning behind lack of `dist` directory in both distributions? I think that vast majority of people (including me) don't want to make custom build but they want to include original version.
3. How about at least adding `postinstall` script in `package.json` which will build library into `dist` directory?

**Comment by lkol** [comment] 2016-11-28 12:50
You probably mean not having dist directory? I would like to see it added too. Currently there's no downloadable version for 4.0.0

**Comment by Forkest** [comment] 2016-11-28 14:56
@lkol, there is neither `dist` nor `src`. The latest `npm` version is just broken.

**Comment by gajus** [comment] 2017-01-11 12:51
Duplicate of https://github.com/gajus/swing/issues/91.

**Closed by gajus** 2017-01-11 12:51 UTC
