### ISSUE TITLE
How to release card if X distance is reached?

### ISSUE THREAD

**Issue by frankenstein-uk** [gajus/swing#39] opened 2015-05-04 08:54 UTC
Hello,

I'm trying to release card once X distance is reached. So you can't drag more than your throwOutConfidence. Card should get released if distance is more than throw out confidence.
What I tried so far is

	eventEmitter.on('_panmove', function (e) {
			var x = lastTranslate.x + e.deltaX,
				y = lastTranslate.y + e.deltaY,
				r = config.rotation(x, y, targetElement, config.maxRotation);
	 
		        if(e.deltaX > 150 || e.deltaX <	-150 )  card.throwOut(x, y);
				
			config.transform(targetElement, x, y, r);
	 
			eventEmitter.trigger('dragmove', {
				target: targetElement,
				throwOutConfidence: config.throwOutConfidence(x, targetElement),
				throwDirection: x < 0 ? Card.DIRECTION_LEFT : Card.DIRECTION_RIGHT
			});
			
	 });

I try to throw out the card once it reached x distance, but this calls the function multiple times, as it's gets triggered few times while dragging.

I'm

**Comment by unbug** [comment] 2015-05-04 14:45
You could do it in ```throwOutConfidence```
```js
gajus.Swing.Stack({{
                    minThrowOutDistance: body.width()*1.3,
                    maxThrowOutDistance: body.width()*1.3,
                    maxRotation: 45,
                    throwOutConfidence: function (offset, element) {
                        var throwOutConfidence = Math.abs(offset) / (element.offsetWidth*.42);
                         // do it here,such as myCard.throwOut();
                        return Math.min(throwOutConfidence, 1);
                    }
                }
```

**Comment by frankenstein-uk** [comment] 2015-05-06 17:29
@unbug Thanks, for suggestion.

 I simply worked that out by amending throwConfidence and removing element on throwend event.

**Comment by gajus** [comment] 2015-07-30 16:24
Duplicate of https://github.com/gajus/swing/issues/27.

**Closed by gajus** 2015-07-30 16:24 UTC
